# Generated by Django 5.2.11 on 2026-02-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('description', models.TextField(verbose_name='Descrição Técnica')),
                ('client_name', models.CharField(max_length=100, verbose_name='Cliente')),
                ('status', models.CharField(choices=[('planning', 'Em Planejamento'), ('active', 'Em Andamento'), ('completed', 'Concluído')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto de Inovação',
                'verbose_name_plural': 'Projetos de Inovação',
                'ordering': ['-created_at'],
            },
        ),
    ]
